### ISSUE TITLE
Fix "Invalid for_each argument"

### ISSUE THREAD

**Issue by kobybr** [MiamiOH/terraform-aws-ssm-parameter-store#4]
Error: Invalid for_each argument
   on .terraform/modules/grok.miamioh_data/ssm_parameter.tf line 3, in resource "aws_ssm_parameter" "miamioh_data":
    3:   for_each = local.resource_parameters_m
 The "for_each" value depends on resource attributes that cannot be determined
 until apply, so Terraform cannot predict how many instances will be created.
 To work around this, use the -target argument to first apply only the
 resources that the for_each depends on.
 Error: Invalid for_each argument
   on .terraform/modules/grok.miamioh_data/ssm_parameter.tf line 20, in resource "aws_ssm_parameter" "miamioh_data_updates":
   20:   for_each = local.resource_parameters_u
 The "for_each" value depends on resource attributes that cannot be determined
 until apply, so Terraform cannot predict how many instances will be created.
 To work around this, use the -target argument to first apply only the
 resources that the for_each depends on.
 Error: Invalid for_each argument
   on .terraform/modules/grok.miamioh_data/ssm_parameter.tf line 32, in data "aws_ssm_parameter" "miamioh_data":
   32:   for_each = local.data_parameters
 The "for_each" value depends on resource attributes that cannot be determined
 until apply, so Terraform cannot predict how many instances will be created.
 To work around this, use the -target argument to first apply only the
 resources that the for_each depends on.

**Comment by edestecd** [comment]
closed by #5
